---
title: “Finally”不能出现在“Try”语句之外
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 94461fece317e01d63dfb13f082b07165454869a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074506"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>“Finally”不能出现在“Try”语句之外

`Finally` 用于完成 `Try...Catch...Finally` 块；因此它只能在块的末尾出现一次。 或者有不必要的 `Finally`，或者 `Finally` 语句出现在其对应 `Try` 块的边界之外。  
  
 **错误 ID:** BC30382  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 找到并删除不必要的 `Finally` 语句。  
  
2. 将 `Finally` 语句移到代码中的适当位置。  
  
## <a name="see-also"></a>请参阅

- [尝试 .。。Catch .。。Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
