---
title: 从“Finally”中分支无效
ms.date: 07/20/2015
f1_keywords:
- bc30101
- vbc30101
helpviewer_keywords:
- BC30101
ms.assetid: 16a0dc29-3657-4373-b77f-38f3cb80e6c9
ms.openlocfilehash: 658874c360f949914f5bedd4cb3858b30441d406
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/23/2020
ms.locfileid: "91083730"
---
# <a name="branching-out-of-a-finally-is-not-valid"></a>从“Finally”中分支无效

`GoTo` 块中的 `Finally` 语句在块外分支。 分支到 `Catch` 或 `Finally` 块或从两个块进行分支是无效的。  
  
 **错误 ID：** BC30101  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
- 删除 `GoTo` 语句，并考虑实现具有决策或循环控制结构的程序逻辑。  
  
## <a name="see-also"></a>请参阅

- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
- [GoTo 语句](../language-reference/statements/goto-statement.md)
- [控制流](../programming-guide/language-features/control-flow/index.md)
